# Generated by Django 6.0.2 on 2026-02-12 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidiary_code', models.CharField(max_length=10, unique=True)),
                ('subsidiary_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='areamaster',
            name='area_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='areamaster',
            name='area_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='areamaster',
            name='subsidiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='accounts.subsidiarymaster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subsidiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subsidiarymaster'),
        ),
        migrations.AlterUniqueTogether(
            name='areamaster',
            unique_together={('subsidiary', 'area_code')},
        ),
    ]
