# Generated by Django 6.0.2 on 2026-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subsidiarymaster_alter_areamaster_area_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='area',
        ),
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='vtc_users', to='accounts.areamaster'),
        ),
    ]
