# Generated by Django 6.0.2 on 2026-02-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_area_customuser_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='area',
            new_name='areas',
        ),
    ]
