# Generated by Django 5.2.4 on 2025-07-28 11:54

import vtc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='independentworker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='independentworker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='independentworker',
            name='father_or_spouse_name',
        ),
        migrations.RemoveField(
            model_name='independentworker',
            name='name',
        ),
        migrations.AddField(
            model_name='independentworker',
            name='aadhar_file',
            field=models.FileField(null=True, upload_to='worker_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='caste',
            field=models.CharField(choices=[('G', 'General'), ('O', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='do_form',
            field=models.FileField(null=True, upload_to='worker_documents/do_forms/', verbose_name='Form O'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='form_o',
            field=models.CharField(max_length=100, null=True, verbose_name='Form O number'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='po',
            field=models.CharField(max_length=100, null=True, verbose_name='Post Office'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='thana',
            field=models.CharField(max_length=100, null=True, verbose_name='Thana'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='village',
            field=models.CharField(max_length=100, null=True, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='independentworker',
            name='dob',
            field=models.DateField(null=True, validators=[vtc.models.IndependentWorker.validate_age], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='independentworker',
            name='mobile',
            field=models.CharField(max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='independentworker',
            name='photo',
            field=models.ImageField(null=True, upload_to='worker_documents/photos/'),
        ),
        migrations.AlterField(
            model_name='independentworker',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
