# Generated by Django 5.2.4 on 2025-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0002_remove_independentworker_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='independentworker',
            name='ID_Card_number',
            field=models.CharField(max_length=100, null=True, verbose_name='ID card number of Trainee'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='father_or_spouse_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Father/Spouse Name'),
        ),
        migrations.AddField(
            model_name='independentworker',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name of Trainee'),
        ),
    ]
