# Generated by Django 5.2.4 on 2025-07-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0003_independentworker_id_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independentworker',
            name='ID_Card_number',
            field=models.CharField(max_length=100, null=True, verbose_name='ID card number of Worker'),
        ),
        migrations.AlterField(
            model_name='independentworker',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name of Worker'),
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('type_of_training', models.CharField(choices=[('Basic', 'Basic'), ('Refresher', 'Refresher'), ('Special', 'Special')], default='Basic', max_length=20)),
                ('aso_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('mm_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('vtc_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('certificate_serial_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='vtc.independentworker')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_appraisal', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='vtc.trainingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='vtc.trainingschedule')),
            ],
            options={
                'unique_together': {('training', 'date')},
            },
        ),
    ]
