# Generated by Django 5.2.4 on 2025-08-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0004_alter_independentworker_id_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='certificate_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
