# Generated by Django 5.2.4 on 2025-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0005_trainingschedule_certificate_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingschedule',
            name='certificate_serial_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
