# Generated by Django 5.2.4 on 2025-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0006_alter_trainingschedule_certificate_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingschedule',
            name='certificate_serial_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
