# Generated by Django 5.2.4 on 2025-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0007_alter_trainingschedule_certificate_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='certificate_serial_number_final',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
