# Generated by Django 5.2.4 on 2025-08-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0008_trainingschedule_certificate_serial_number_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='nature_of_training',
            field=models.CharField(max_length=20, null=True, verbose_name='Nature of Training'),
        ),
    ]
