# Generated by Django 5.2.4 on 2025-08-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0009_trainingschedule_nature_of_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingschedule',
            name='nature_of_training',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
