# Generated by Django 5.2.4 on 2025-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0010_alter_trainingschedule_nature_of_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingschedule',
            name='nature_of_training',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
