# Generated by Django 5.2.4 on 2025-08-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0011_alter_trainingschedule_nature_of_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
