# Generated by Django 5.2.4 on 2025-08-18 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0012_trainingschedule_contractor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='independentworker',
        #     name='user',
        #     field=models.ForeignKey(null, on_delete=django.db.models.deletion.CASCADE, related_name='independent_workers', to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
    ]
