# Generated by Django 5.2.4 on 2025-08-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0014_independentworker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='independentworker',
            old_name='user',
            new_name='created_by',
        ),
    ]
