# Generated by Django 5.2.4 on 2025-08-19 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0016_trainingschedule_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='aso_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='aso_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aso_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='mm_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='mm_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mm_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='vtc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='vtc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vtc_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
