# Generated by Django 5.2.4 on 2025-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0017_trainingschedule_aso_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingattendance',
            name='present',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], max_length=10),
        ),
    ]
