# Generated by Django 5.2.4 on 2025-09-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0018_alter_trainingattendance_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='attendance_field_file',
            field=models.FileField(null=True, upload_to='worker_documents/attendancefield/'),
        ),
    ]
