# Generated by Django 5.2.4 on 2025-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0019_trainingschedule_attendance_field_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingresult',
            name='attendance_field_file',
            field=models.FileField(null=True, upload_to='worker_documents/attendancefield/'),
        ),
    ]
