# Generated by Django 6.0.2 on 2026-02-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0021_alter_trainingresult_attendance_field_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
