# Generated by Django 6.0.2 on 2026-03-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0022_trainingschedule_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
