# Generated by Django 6.0.2 on 2026-03-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0023_trainingattendance_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
