# Generated by Django 6.0.2 on 2026-06-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0024_trainingschedule_area_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiometricAttendanceRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_date', models.DateField()),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('employee_code', 'attendance_date')},
            },
        ),
    ]
