# Generated by Django 6.0.2 on 2026-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc', '0025_biometricapilog_biometricattendanceraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricapilog',
            name='employee_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
